version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: "increase"
    open-pull-requests-limit: 7
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"

      nextjs:
        patterns:
          - "next"
          - "@next/eslint-plugin-next"
          - "eslint-config-next"

      material-ui:
        patterns:
          - "@mui/material"
          - "@mui/icons-material"

      ag-grid:
        patterns:
          - "ag-grid-*"

      es-lint:
        patterns:
          - "eslint"
          - "@eslint/js"
          - "@typescript-eslint/eslint-plugin"
          - "@typescript-eslint/parser"
          - "typescript-eslint"
