services:
  dev:
    tty: true
    hostname: devcontainer
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.devcontainer
      args:
        PROJECT_NAME: next-common
    # ports:
    #   - "3001:3001"
    # environment:
    #   PORT: 3001
    volumes:
      # Workspace
      - ..:/workspace/next-common:cached
      # Home
      - ../volumes/home:/home/vscode:cached
      # Additional scripts
      - ~/scripts:/home/vscode/scripts:ro
